### ISSUE TITLE
nva tools fail at PCI initialization

### ISSUE THREAD

**Issue by vbe0201** [envytools/envytools#210]
Hello, I'm currently looking into using the nva tools, specifically `nvatiming`, `nvafucstart` and `nvagetpmu`. I have the proprietary NVIDIA driver running on my machine since the README states that it is a requirement for `nvagetpmu`. But for some reason, whatever tool I invoke, it opts out at PCI initialization with the following error message:

```
❯ sudo nvalist
WARN: Can't probe 0000:26:00.0
PCI init failure!
```

Given that warning, I tried to query the device with `lspci` and that indeed seems to be my GPU.

```
❯ lspci -vv -s 26:00
26:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. Device 8598
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Interrupt: pin A routed to IRQ 72
	IOMMU group: 15
	Region 0: Memory at f6000000 (32-bit, non-prefetchable) [size=16M]
	Region 1: Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Region 3: Memory at f0000000 (64-bit, prefetchable) [size=32M]
	Region 5: I/O ports at e000 [size=128]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia
```

System and dependency versions that were used when building latest envytools master (9353a869e9133d3e914257435db9a216a30bc625):

* Arch Linux with Linux kernel 5.7.10
* libpciaccess 0.16
* libx11 1.6.9
* libxext 1.3.4
* Python 3.8.3
* Cython 0.29.20

I had several people reproducing the issue, any help with this would be greatly appreciated. Please let me know if I missed any important details.

**Comment by evelikov** [comment]
Pretty sure the nva tools need root privileges

**Comment by imirkin** [comment]
This happened to @karolherbst recently. Is there a driver loaded? If so, you have to boot with iommu=relaxed.

**Comment by vbe0201** [comment]
@evelikov @imirkin Thanks for the answers! I edited `/etc/default/grub` to `GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet iommu=relaxed"` and restarted my machine, sadly the error message for `nvalist` and the other tools still stays the same as above. Any ideas?

**Comment by karolherbst** [comment]
> @evelikov @imirkin Thanks for the answers! I edited `/etc/default/grub` to `GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet iommu=relaxed"` and restarted my machine, sadly the error message for `nvalist` and the other tools still stays the same as above. Any ideas?

just editing the file isn't enough. You either have to regenerate your grub.conf or have to adjust your grubenv files depending on your distribution.

**Comment by vbe0201** [comment]
Thanks for pointing out, that solved my issue. After some investigation, the `iommu` option apparently doesn't support a `relaxed` option and thus I tried `iomem=relaxed` and regenerated my grub config. The tools work as expected now. If anyone else stumbles across this issue, I hope this helps.
