### ISSUE TITLE
Any way to read VRAM size from the hardware ?

### ISSUE THREAD

**Issue by terminatorul** [envytools/envytools#223]
Hello!

I am trying to read VRAM size from the hardware (like from the configuration in BAR0), but I found nothing about this in the online envytools documentation. Is there a way to read VRAM size from the GPU ?

Thank you
Timothy Madden

**Comment by mupuf** [comment]
You may have more luck in Nouveau's code: https://github.com/skeggsb/nouveau/tree/master/drm/nouveau/nvkm/subdev/fb

**Comment by terminatorul** [comment]
Thank you.

I am trying to read that but there is a lot of code there and too difficult to follow. I see for older architectures the size is read from vBIOS at a fixed offset given by the subsystem vendor. For for a newer architecture (I need Turing RTX 2000 / GTX 1600) I still don't understand how the size is found...

**Comment by mupuf** [comment]
Then sorry, you already know more than I do!

**Comment by imirkin** [comment]
I'm pretty rusty on the details. There's various bits that differ by gen, and also we know more about the memory of older than newer gens.

You can trace it through, e.g for a TU102+ board:

https://cgit.freedesktop.org/drm/drm/tree/drivers/gpu/drm/nouveau/nvkm/subdev/fb/tu102.c

will use gp102_fb_vidmem_size, which is defined here:

https://cgit.freedesktop.org/drm/drm/tree/drivers/gpu/drm/nouveau/nvkm/subdev/fb/gp102.c

which basically works out to reading MMIO register 0x100ce0 and doing some math.

**Comment by terminatorul** [comment]
Thank you, makes sense now. I assume the tu102.c file is used for any Turing GPU ?

How do I identify the GPU as Turing ? Has the PMC registers for  ID and NEW_ID stayed the same and works for newer generations (the envytools documentation appears to stop at Fermi..) Or to people have to use the PCI ID range instead (that sounds worse ...) ?

**Comment by imirkin** [comment]
It's a bit roundabout ... it all starts here:

https://cgit.freedesktop.org/drm/drm/tree/drivers/gpu/drm/nouveau/nvkm/engine/device/base.c#n3221

So I'm guessing you have one of these 0x16x's, which will work out as

	.fb       = { 0x00000001, tu102_fb_new },

Which you can in turn trace through as I mentioned. If I guessed wrong, look at the "correct" chipset and trace from there.

The BOOT0 register continues to identify the chipset (MMIO register 0x000000).

**Comment by terminatorul** [comment]
ty
