### ISSUE TITLE
Fails to find python3 module.

### ISSUE THREAD

**Issue by orbea** [envytools/envytools#48]
When compiling envytools in Slackware it fails to find the python3 module since the pkg-config file is called `python-3.5` not `python3`. 
```
-- Checking for module 'python3'
--   No package 'python3' found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
Warning: nvapy won't be built because of un-met dependencies (python and cython)
```

So I traced the issue to `nva/CMakeLists.txt` where there is this line, `pkg_check_modules(PC_PYTHON python3)` and found that I could work around it with `sed -i 's/python3/python-3.5/' nva/CMakeLists.txt`.

I would appreciate if a sed was not necessary though.

**Comment by koriakin** [comment]
Thanks for the report, but I'm afraid I don't know how to do it better - fixing the required python at 3.5 is obviously a no-go.  I don't have a Slackware installation to test, either.  Do you have any idea how python detection works in other packages?

**Comment by orbea** [comment]
Unfortunately I don't know the best way to fix this either. I have seen other projects check for multiple different variants of the python3 pkg-config file, but there might be a better way.

**Comment by orbea** [comment]
After asking in the cmake irc channel at freenode I was suggested `pkg_search_module()`, this seems to be at least a better way.
```
diff -urN ../envytools/nva/CMakeLists.txt envytools/nva/CMakeLists.txt
--- ../envytools/nva/CMakeLists.txt	2016-03-14 11:35:09.615229628 -0700
+++ envytools/nva/CMakeLists.txt	2016-03-14 11:45:13.312499651 -0700
@@ -7,7 +7,7 @@
 	pkg_check_modules(PC_PCIACCESS pciaccess)
 	pkg_check_modules(PC_X11 x11)
 	pkg_check_modules(PC_XEXT xext)
-	pkg_check_modules(PC_PYTHON python3)
+	pkg_search_module(PC_PYTHON python3 python-3.5)
 	find_package (Threads)
 	find_program (CYTHON_EXECUTABLE cython)
 
```

**Comment by koriakin** [comment]
Ugly, but let's go with it.  Do you want to make a pull request?

**Comment by orbea** [comment]
My first pull request, I hope I did it right... :)

https://github.com/envytools/envytools/pull/49
